// ============================================================================
//  lv_conf.h — minimal LVGL 9.3 configuration.
//
//  Only the deviations from the upstream template defaults are listed;
//  every undefined option falls back to the internal default in
//  lv_conf_internal.h.  Rendering is single-threaded: lv_*() is only ever
//  called from UiTask, so LV_USE_OS stays NONE.
// ============================================================================
#pragma once

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

// Heap: builtin TLSF pool in internal SRAM.  88 KB fits all 11 apps with the
// lazy settings pages (heavy pages + keyboard are destroyed on close) while
// still leaving the internal block the TLS handshake needs.
#define LV_USE_STDLIB_MALLOC LV_STDLIB_BUILTIN
#define LV_MEM_SIZE (88 * 1024)

#define LV_USE_OS LV_OS_NONE

// Tick comes from millis() via lv_tick_set_cb().
#define LV_TICK_CUSTOM 0

#define LV_DPI_DEF 170

// --- Fonts ----------------------------------------------------------------
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_32 1
#define LV_FONT_MONTSERRAT_48 1

// Cyrillic-capable UI fonts (Arial + FontAwesome glyphs, generated by
// tools/fonts via lv_font_conv).  Used for all Russian text and for the
// on-screen keyboard; symbols live in the FontAwesome range 0xF000-0xF2E0.
#define LV_FONT_CUSTOM_DECLARE \
    extern const lv_font_t ui_font_ru_16; \
    extern const lv_font_t ui_font_ru_20; \
    extern const lv_font_t ui_font_ru_28;

// --- Widgets (defaults are fine; disable nothing we use) -------------------
#define LV_USE_FLEX 1

// --- Deselect everything the prototype does not need to save flash --------
#define LV_USE_OBJ_NAME 0
